config/routes.rb
Rails.application.routes.draw do

  devise_for :writers

  resources :posts

  root 'posts#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :customer
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :categories
  paginates_per 2

  def pub_date
    created_at.strftime('%Y/%m/%d %H:%M')
  end
end

app/models/writer.rb
class Writer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_q

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def set_q
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :set_q

  def new
    @post = Post.new
  end

  def create
    # retrieve the user input
    @post = Post.new(post_params)
    # save the user input
    @post.save
    # throw the user input data to show
    redirect_to "/posts/#{@post.id}"
  end

  def show
  end

  def index
    #@posts = Post.page(params[:page])
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page])
  end

  def edit
    # find and grab the data from the database and input it into edittable fields
    # update the new data into the database
    # redirect the page to the show page, showing the newly updated information
    #BUT IN REALITY YOU DONT NEED ANY OF THAT. YOU ONLY NEED THE @post = Post.find(params[:id]) SET IN THE set_post AND CALLED IN THE before_action ABOVE.
  end

  def update
     #YOU ONLY NEED THE @post = Post.find(params[:id]) SET IN THE set_post AND CALLED IN THE before_action ABOVE.

    # update_attributesメソッドで上書き保存
    @post.update_attributes(post_params)
    redirect_to "/posts/#{@post.id}"
  end

  def destroy
     #YOU ONLY NEED THE @post = Post.find(params[:id]) SET IN THE set_post AND CALLED IN THE before_action ABOVE.
     @post.destroy
     redirect_to "/posts/"
  end

private

  def post_params
    params.require(:post).permit(:title, :body, :category_id)
  end

  def set_post
    @post = Post.find(params[:id])
  end

  def set_q
    @q = Post.ransack(params[:q])
    @posts = @q.result.page(params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def find_category_title(category_id)
    category = Category.find(category_id)
    category.title
  end
end
# This method can only be used in the view folder/files.
# This method is used in the "show.html.erb" in the Category section.

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>

<!-- Latest compiled and minified CSS -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
 <!-- Optional theme -->
 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
 <!-- Latest compiled and minified JavaScript -->
 <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/posts">My Blog</a>
    </div>
    <%= search_form_for @q, class: "navbar-form navbar-left" do |f| %>
      <div class="form-group">
        <%= f.search_field :title_or_body_cont, class: "form-control" %>
        <%= f.submit "検索", class: "btn btn-default" %>
      </div>
    <% end %>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/posts/new">New Post</a></li>
        <% if present? %>
        <li><%= link_to 'Change Settings', edit_writer_registration_path %></a></li>
        <li><%= link_to 'Log out', destroy_writer_session_path, method: :delete %></a></li>
        <% else %>
        <li><%= link_to 'Sign Up', new_writer_registration_path %></a></li>
        <li><%= link_to 'Log in', new_writer_session_path %></a></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/posts/edit.html.erb
<div class="col-md-12">
  <h1>Editing Page</h1>
    <%= form_for @post, url: { action: :update } do |f| %>

    <div class="form-group">
      <%= f.label "Title" %>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label "Category" %>
      <%= f.collection_select(:category_id, Category.all, :id, :title, class: "form_control") %>
    </div>

    <div class="form-group">
      <%= f.label "Body" %>
      <%= f.text_area :body, class: "form-control"%>
    </div>

<%= f.submit 'Update' %>

<% end %>
</div>

app/views/posts/index.html.erb
<h2>My Blog</h2>

<div class ="container">
 <div class ="row">
   <div class ="col-md-8">
     <% @posts.each do |post| %>
         <div class="article">
           <h2><%= post.title %></h2>
           <p><%= post.category %> <%= post.pub_date %></p>
           <p><%= truncate(post.body, length: 50) %></p>
           <p>
             <%= link_to "続きを読む", post_path(post.id), class: 'btn btn-default' %>
           </p>
         </div>
     <% end %>
     <%= paginate @posts %>
   </div>

  <div class = "col-md-4">
    <div class="thumbnail">
      <% author = Author.first %>
      <img src="<%= author.image_url %>" alt="著者イメージ">
      <div class="caption">
        <h3><%= author.name %></h3>
        <p><%= author.description %></p>
      </div>
     </div>

     <div class="list-group">
    <% @posts.each_with_index do |post, index| %>
      <%# ６個目以上の記事の場合はBreak（each文をその場で終わらせる） %>
      <% if index >= 5
           break
         end
      %>
      <%# link_to post.title, post_path(post.id), class: "list-group-item" %>
      <a href="/posts/<%= post.id %>" class="list-group-item"><%= post.title %></a>
    <% end %>
  </div>
   </div>
 </div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post, url: { action: :create } do |f| %>
<div class="form-group">
<%= f.label "Title" %>
<%= f.text_field :title, class: "form-control"%>
</div>

<div class="form-group">
<%= f.label "Body" %>
<%= f.text_area :body, class: "form-control"%>
</div>

<div class="form-group">
<%= f.label "Category" %>
<%= f.text_field :category, class: "form-control"%>
</div>


<%= f.submit 'Post', class: "btn btn-primary"%>

<% end %>

app/views/posts/show.html.erb
<div class="col-md-12>"
<p>Title:<%= @post.title %></b></p>

<p>Category:<%= find_category_title(@post.category_id) %></p>
<p>Date of post:<%= @post.created_at %></p>

<p><%= simple_format(@post.body) %></p>

<%= link_to 'edit', edit_post_path %>
<%= link_to 'delete', post_path, method: :delete %>

</div>